{% set version = '1.3-3' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-bdsmatrix
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/bdsmatrix_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/bdsmatrix/bdsmatrix_{{ version }}.tar.gz
  sha256: 70ea81708c97dedd483a5d3866d2e906fa0e9098ff854c41cf0746fbc8dfad9d

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]

  host:
    - r-base

  run:
    - r-base
    - {{native}}gcc-libs         # [win]

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('bdsmatrix')"           # [not win]
    - "\"%R%\" -e \"library('bdsmatrix')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=bdsmatrix
  license: LGPL-2
  summary: 'This is a special case of sparse matrices, used by coxme. '

  license_family: LGPL
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/LGPL-2'

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: bdsmatrix
# Title: Routines for Block Diagonal Symmetric Matrices
# Maintainer: Terry Therneau <therneau@mayo.edu>
# Version: 1.3-3
# Date: 2017-12-20
# Depends: methods, R (>= 2.0.0)
# LazyData: Yes
# LazyLoad: Yes
# Author: Terry Therneau
# Description: This is a special case of sparse matrices, used by coxme.
# License: LGPL-2
# Collate: bdsmatrix.R gchol.R gchol.bdsmatrix.R as.matrix.bdsmatrix.R bdsBlock.R bdsI.R bdsmatrix.ibd.R bdsmatrix.reconcile.R diag.bdsmatrix.R listbdsmatrix.R multiply.bdsmatrix.R solve.bdsmatrix.R solve.gchol.R solve.gchol.bdsmatrix.R backsolve.R
# NeedsCompilation: yes
# Packaged: 2017-12-21 15:52:14 UTC; therneau
# Repository: CRAN
# Date/Publication: 2017-12-21 21:24:50 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
