travis:
  secure:
    BINSTAR_TOKEN: I/LLp5BPQfkE2drIiUw4Y/BjgEXsR7co9TqzpZJP+wul9jgUO/6h4CuVcpkVkVYZfAw4cK8DX4QqX7efWsUAqUMa/TmI3N+i7xIl069lJz5CLTeCcIkCqIljkEBxgng1E35jFTwvbsumaVILRB1zURKeAwr6Wf8ar0+luKp64/NsL5Ea4fMVRHveg7ltZ+f4/K83HhGOVsbUdrXRDK3KBj+zdvI08Kb8HGs5l4ZYS7Qrq5O8ucvIj5Z7uNvUvPh5pTyi3ww5Dc8N5Qu7HFnOsVMvIux1DtZbJHlI26gpGLl3AD7szC16uYEgKOCbnZ8Ae9OEzqvqFrSr3ZCW9/Q4HLbx1qJ2y6eGs/WS4Kl9EiuxxRBiejf0J7laTU2/zThBFw4EXDbBXs1/G/RhUKYoHSqMBhd8yvHh4HU9MhuAOsQ9scUGD9BeHrAq9wYowIgxAvmQt7K8w0Uyp4uttCPaSmgsID6UrhqlWSM9NigeIhWc3z2qZBF7dPTiC7XDvT/UiJgZypk4Qu9p7Qj8a8TMJGD2M5KiQ7qjPUHtxk6gm17r9uPWJq3Pk/cE2liGJsNe8k2Bi6rAhoAu7MbXeOHYHgaXm0qa59LqgxAJrPUUBzVoJfLmanrQn9UvuTcK4hT2A7BL4JJm0HriehsroGLssIxg1igu3Pj9wx7x14klojs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
